name: Deploy
run-name: Deploy 🚀
on: [push]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Compile MyMcRealms
        run: dotnet publish --runtime linux-arm64
      - name: Deploy compile binary and dll files to server
        run: scp -r -P 9476 MyMcRealms\bin\Release\net8.0\linux-arm64\publish\* root@ssh.surf:/root/MyMcRealms
