@MyMcRealms_HostAddress = http://localhost:8080

GET {{MyMcRealms_HostAddress}}/mco/available
Accept: application/json

###

GET {{MyMcRealms_HostAddress}}/mco/client/compatible
Accept: application/json

###

GET {{MyMcRealms_HostAddress}}/worlds
Accept: application/json

###