name: Deploy
run-name: Deploy 🚀
on: [push]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install dotnet
        run: |
          wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh
          chmod +x dotnet-install.sh
          ./dotnet-install.sh
      - name: Compile MyMcRealms
        run: /home/runner/.dotnet/dotnet publish --runtime linux-arm64
      - name: Install ssh agent
        uses: webfactory/ssh-agent@v0.9.0
      - name: Stop the realms server for the deployment
        run: ssh -o StrictHostKeyChecking=no -p 9476 my-mc.link "pm2 stop 0"
      - name: Deploy compiled binary and dll files to server
        run: scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r MyMcRealms/bin/Release/net8.0/linux-arm64/publish/* my-mc.link:/home/cyber/MyMcRealms
      - name: Start the realms server again
        run: ssh -o StrictHostKeyChecking=no -p my-mc.link "pm2 start 0"
